import turtle

t = turtle.Pen()


def sztanga(kratka):
    t.down()
    t.right(90)
    t.fd(kratka * 3)
    t.left(180)
    t.fd(kratka * 1.5)
    t.right(90)
    t.fd(kratka / 2)
    t.right(90)
    t.bk(kratka)
    t.fd(kratka * 2)
    t.bk(kratka)
    t.left(90)
    t.fd(kratka / 2)
    t.left(90)
    t.bk(kratka / 2)
    t.fd(kratka)
    t.bk(kratka / 2)
    t.right(90)
    t.fd(kratka * 6)
    t.left(90)
    t.bk(kratka / 2)
    t.fd(kratka)
    t.bk(kratka / 2)
    t.right(90)
    t.fd(kratka / 2)
    t.left(90)
    t.bk(kratka)
    t.fd(kratka * 2)
    t.bk(kratka)
    t.right(90)
    t.fd(kratka / 2)
    t.left(90)
    t.bk(kratka * 1.5)
    t.fd(kratka * 3)


def atleta(gora, kratka):
    if gora:
        t.up()
        t.fd(kratka)
        t.left(90)
        t.fd(kratka * 7.5)
        t.right(90)
        sztanga(kratka)
        t.up()
        t.bk(kratka * 7.5)
        t.left(90)
        t.fd(kratka * 2)
    else:
        t.fd(kratka)
        t.left(90)
        t.fd(kratka * 3)
        t.right(90)
        sztanga(kratka)
        t.up()
        t.bk(kratka * 3)
        t.left(90)
        t.fd(kratka * 2)
        t.down()
    t.down()
    t.fd(kratka)
    t.right(90)
    t.fd(kratka * 2)
    t.left(90)
    t.color("black", "green")
    t.begin_fill()
    for i in range(4):
        t.fd(kratka * 2)
        t.right(90)
    t.end_fill()
    t.fd(kratka * 2)
    t.left(90)
    t.fd(kratka * 2)
    t.right(90)
    t.fd(kratka)
    t.up()
    t.right(90)
    t.fd(kratka * 4)
    t.right(90)
    t.fd(kratka * 1.5)
    t.down()
    t.left(90)
    t.color("black", "yellow")
    t.begin_fill()
    for i in range(4):
        t.fd(kratka)
        t.right(90)
    t.end_fill()
    t.left(90)
    t.fd(kratka * 1.5)
    if gora:
        t.right(90)
        t.fd(kratka * 2)
        t.right(90)
        t.up()
        t.fd(kratka * 4)
        t.right(90)
        t.down()
        t.fd(kratka * 2)
        t.right(90)
        t.fd(kratka)
        t.left(180)
        t.up()
        t.fd(kratka * 3)
        t.right(90)
        t.fd(kratka * 4)
        t.left(90)
    else:
        t.left(90)
        t.fd(kratka * 2)
        t.left(90)
        t.up()
        t.fd(kratka * 4)
        t.left(90)
        t.down()
        t.fd(kratka * 2)
        t.left(90)
        t.fd(kratka)
        t.left(180)
        t.up()
        t.fd(kratka * 3)
        t.right(90)
        t.fd(kratka * 4)
        t.left(90)


def atleci(ilu):
    t.up()
    kratka = 760 / (ilu * 9 - 1)
    t.bk(760 / 2 + kratka)
    for numer in range(ilu):
        atleta(numer % 2, kratka)


t.speed(0)
atleci(10)
