[workspace]

members = [
	"repetitions/repetitions_rust",
	"permutations/permutations_rust",
	"weird_algorithm/weird_algorithm_rust",
	"increasing_array/increasing_array_rust",
	"number_spiral/number_spiral_rust",
]
